### PR TITLE
[ISSUE #264] Bug fixed, should not pass annotations into podTemplate

### LINKED ISSUE #264: [BUG] 【containerized workload】 Updating the trait of application will result in all workload rebuilding
1. We have the following application configuration：
```
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: example-component-1
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      containers:
        - name: nginx
          image: nginx
---
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: example-component-2
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      containers:
        - name: nginx
          image: nginx
---
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: example-appconfig
spec:
  components:
    - componentName: example-component-1
      traits:
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: ManualScalerTrait
            spec:
              replicaCount: 3
    - componentName: example-component-2
      traits:
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: ManualScalerTrait
            spec:
              replicaCount: 1
```

2. Check the generated deployment information as follows:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"core.oam.dev/v1alpha2","kind":"ApplicationConfiguration","metadata":{"annotations":{},"name":"example-appconfig","namespace":"test"},"spec":{"components":[{"componentName":"example-component-1","traits":[{"trait":{"apiVersion":"core.oam.dev/v1alpha2","kind":"ManualScalerTrait","spec":{"replicaCount":3}}}]},{"componentName":"example-component-2","traits":[{"trait":{"apiVersion":"core.oam.dev/v1alpha2","kind":"ManualScalerTrait","spec":{"replicaCount":1}}}]}]}}
  creationTimestamp: "2020-10-23T10:11:05Z"
  generation: 2
  labels:
    app.oam.dev/component: example-component-1
    app.oam.dev/name: example-appconfig
    app.oam.dev/resourceType: WORKLOAD
    app.oam.dev/revision: example-component-1-v1
  managedFields:
    ...
  name: example-component-1
  namespace: test
  ownerReferences:
  - apiVersion: core.oam.dev/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: ContainerizedWorkload
    name: example-component-1
    uid: 4aa79e56-8f1d-4969-bdc0-cdf365d5c7c0
  - apiVersion: core.oam.dev/v1alpha2
    blockOwnerDeletion: true
    controller: false
    kind: ManualScalerTrait
    name: example-component-1-trait-545647b965
    uid: fd22e87a-3009-4394-a7e9-12ed8713e0cb
  resourceVersion: "149974797"
  selfLink: /apis/apps/v1/namespaces/test/deployments/example-component-1
  uid: f2f773a8-c76a-472f-9b08-15946f0c812b
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      containerizedworkload.oam.crossplane.io: 4aa79e56-8f1d-4969-bdc0-cdf365d5c7c0
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"core.oam.dev/v1alpha2","kind":"ApplicationConfiguration","metadata":{"annotations":{},"name":"example-appconfig","namespace":"test"},"spec":{"components":[{"componentName":"example-component-1","traits":[{"trait":{"apiVersion":"core.oam.dev/v1alpha2","kind":"ManualScalerTrait","spec":{"replicaCount":3}}}]},{"componentName":"example-component-2","traits":[{"trait":{"apiVersion":"core.oam.dev/v1alpha2","kind":"ManualScalerTrait","spec":{"replicaCount":1}}}]}]}}
      creationTimestamp: null
      labels:
        app.oam.dev/component: example-component-1
        app.oam.dev/name: example-appconfig
        app.oam.dev/resourceType: WORKLOAD
        app.oam.dev/revision: example-component-1-v1
        containerizedworkload.oam.crossplane.io: 4aa79e56-8f1d-4969-bdc0-cdf365d5c7c0
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-10-23T10:11:23Z"
    lastUpdateTime: "2020-10-23T10:11:23Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-10-23T10:11:05Z"
    lastUpdateTime: "2020-10-23T10:11:23Z"
    message: ReplicaSet "example-component-1-54b6465b7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
```

Please pay attention to the spec.template.metadata.annotations information of deployment
```
kubectl.kubernetes.io/last-applied-configuration: ...
```

3. Then we update the trait of ApplicationConfiguration

```
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: example-component-1
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      containers:
        - name: nginx
          image: nginx
---
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: example-component-2
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      containers:
        - name: nginx
          image: nginx
---
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: example-appconfig
spec:
  components:
    - componentName: example-component-1
      traits:
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: ManualScalerTrait
            spec:
              replicaCount: 1
    - componentName: example-component-2
      traits:
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: ManualScalerTrait
            spec:
              replicaCount: 1
```

4. Then we found that all pods have been rebuilt, this does not meet our expectations。
```
# kubectl get pod -n test
NAME                                   READY   STATUS              RESTARTS   AGE
example-component-1-54b6465b7-4qfjd    0/1     Terminating         0          8m17s
example-component-1-56bc8b8c8f-fnpdw   1/1     Running             0          7s
example-component-2-5968fc5c66-8tt6n   0/1     ContainerCreating   0          7s
example-component-2-6765c758fb-pp7sg   1/1     Running             0          8m17s
```

5. Then we check the deployment at this time

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"core.oam.dev/v1alpha2","kind":"ApplicationConfiguration","metadata":{"annotations":{},"name":"example-appconfig","namespace":"test"},"spec":{"components":[{"componentName":"example-component-1","traits":[{"trait":{"apiVersion":"core.oam.dev/v1alpha2","kind":"ManualScalerTrait","spec":{"replicaCount":1}}}]},{"componentName":"example-component-2","traits":[{"trait":{"apiVersion":"core.oam.dev/v1alpha2","kind":"ManualScalerTrait","spec":{"replicaCount":1}}}]}]}}
  creationTimestamp: "2020-10-23T10:11:05Z"
  generation: 4
  labels:
    app.oam.dev/component: example-component-1
    app.oam.dev/name: example-appconfig
    app.oam.dev/resourceType: WORKLOAD
    app.oam.dev/revision: example-component-1-v1
  managedFields:
  ...
  name: example-component-1
  namespace: test
  ownerReferences:
  - apiVersion: core.oam.dev/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: ContainerizedWorkload
    name: example-component-1
    uid: 4aa79e56-8f1d-4969-bdc0-cdf365d5c7c0
  - apiVersion: core.oam.dev/v1alpha2
    blockOwnerDeletion: true
    controller: false
    kind: ManualScalerTrait
    name: example-component-1-trait-545647b965
    uid: fd22e87a-3009-4394-a7e9-12ed8713e0cb
  resourceVersion: "149977304"
  selfLink: /apis/apps/v1/namespaces/test/deployments/example-component-1
  uid: f2f773a8-c76a-472f-9b08-15946f0c812b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      containerizedworkload.oam.crossplane.io: 4aa79e56-8f1d-4969-bdc0-cdf365d5c7c0
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"core.oam.dev/v1alpha2","kind":"ApplicationConfiguration","metadata":{"annotations":{},"name":"example-appconfig","namespace":"test"},"spec":{"components":[{"componentName":"example-component-1","traits":[{"trait":{"apiVersion":"core.oam.dev/v1alpha2","kind":"ManualScalerTrait","spec":{"replicaCount":1}}}]},{"componentName":"example-component-2","traits":[{"trait":{"apiVersion":"core.oam.dev/v1alpha2","kind":"ManualScalerTrait","spec":{"replicaCount":1}}}]}]}}
      creationTimestamp: null
      labels:
        app.oam.dev/component: example-component-1
        app.oam.dev/name: example-appconfig
        app.oam.dev/resourceType: WORKLOAD
        app.oam.dev/revision: example-component-1-v1
        containerizedworkload.oam.crossplane.io: 4aa79e56-8f1d-4969-bdc0-cdf365d5c7c0
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-10-23T10:11:23Z"
    lastUpdateTime: "2020-10-23T10:11:23Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-10-23T10:11:05Z"
    lastUpdateTime: "2020-10-23T10:19:21Z"
    message: ReplicaSet "example-component-1-56bc8b8c8f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

We found that the deployment revision has now become 2，and spec.template.metadata.annotationsalso changed。So we need to prohibit the annotation of application configuration（ kubectl.kubernetes.io/last -Applied configuration)  passed to deployment and pod。

**Note: A Deployment's revision is created when a Deployment's rollout is triggered. This means that the new revision is created if and only if the Deployment's Pod template (.spec.template) is changed, for example if you update the labels or container images of the template. Other updates, such as scaling the Deployment, do not create a Deployment revision, so that you can facilitate simultaneous manual- or auto-scaling. This means that when you roll back to an earlier revision, only the Deployment's Pod template part is rolled back.**

### PR DESCRIPTION
**Pull request by linjiemiao**
We shouldn't pass annotation into podTemplate in ContainerizedWorkload.

fix #264

### CODE REVIEW

File: test/e2e-test/containerized_workload_test.go [hunk 1]
```diff
@@ -268,7 +268,17 @@ var _ = Describe("ContainerizedWorkload", func() {
 			},
 			time.Second*60, time.Second*5).Should(BeEquivalentTo(replica))
 		Expect(*deploy.Spec.Replicas).Should(BeEquivalentTo(replica))
-
+		By("Verify pod annotations should not contain kubectl.kubernetes.io/last-applied-configuration")
+		Eventually(
+			func() bool {
+				k8sClient.Get(ctx, objectKey, deploy)
+				annotations := deploy.Spec.Template.Annotations
+				if _, ok := annotations["kubectl.kubernetes.io/last-applied-configuration"]; ok {
```
Comment (wonderflow) [inline test/e2e-test/containerized_workload_test.go:276]: the workload created by go-client will not have this annotations. Let's create one in AppConfig and Check.

Comment (linjiemiao) [reply test/e2e-test/containerized_workload_test.go]: ok, i have already edited it.

**Review by wonderflow — APPROVED** [review]
